ALL_SEQUENCE_CATEGORY = [
    "Spencer Multi Touch Master Sequence",
    "2nd Multi Touch",
    "Nov. Seq.",
    "Rory-2023",
    "ZI Intent (Sidonie) ",
    "New Year Start",
    "Portal Sequence",
    "One Pager Sequence",
    "Regionals",
    "Rent-Burdened",
    "Cory/Louis Feb 2023",
    "Mina/Katie Feb 2023 Outreach",
    "KL SL Clone (feb) ",
    "Feb/March 2023 - cold out reach",
    "Ariel/Fiona Feb/March 2023 - cold outreach",
    "Ally Yates Feb Seq 2023",
    "ChatGPT",
    "March/April 23- calls, Allison ",
    "Fiona/Ariel April",
    "Fiona/Zach April ",
    "Multifamily Insider",
    "Fiona/Spencer April ",
    "JE Q2 Email Sequence - Emails",
    "JE Q2 Email Sequence - Calls",
    "Mina's June/July ",
    "Rory June/July  Clone",
    "AK Q2",
    "Morgan Q2 Email Sequence - Emails ",
    "JM Email Sequence June / July",
    "Conam",
    "New Sequence 6.23",
    "ZB June 2023 *",
    "Ally/Mina June/July",
    "Benefits",
    "JM July 23",
    "Reviews",
    "Budgets",
    "AK shared - PM software",
    "JE shared - PM software (clone)",
    "Mina Oct 2023 Outreach",
    "ZB October",
]
