import openai
from dotenv import load_dotenv
import os

# Replace 'your-api-key' with your actual OpenAI API key
load_dotenv()
openai.api_key = os.environ.get("OPEN-API-KEY")
"Please ensure that responses are concise, no more than 100 words each, and that they provide clear, complete information for each inquiry"
# FAQ_list = [
# {"question": "Where do I sign up for Flex?", "answer": "Sign up for Flex through residents' browser HERE or through the Flex app! You can download the app on Google Play or the App Store!"},
# {"question": "When can I sign up for Flex?", "answer": "If residents successfully sign up by the 3rd day of the month, there may still be enough time to process residents' payment for that month. If residents enroll with Flex after the 3rd, we will set residents up for rent payment in the following month."},
# {"question": "How does Flex pay my rent?", "answer": "After enrolling with Flex, we automatically make residents' rent payment directly to residents' property when due each month. Flex pays residents' rent between the last day of the prior month through the first 5 days of the month. Funds must be available by 1pm EST on the 5th in order for a rent payment to be successfully submitted."},
# {"question": "How much is the Flex membership fee?", "answer": "Flex charges a standard monthly membership fee of $14.99. Flex also charges a payment processing fee, a percentage of the monthly rent payment based on the chosen payment method (0.75% for debit card and 3% for credit card), assessed on each repayment."},
# {"question": "How does the repayment schedule work again?", "answer": "Each month, residents pay us back in two payments - residents' 1st payment when residents' rent is due and residents' 2nd payment on the 15th of the month or residents' rescheduled date within the month. You can manage residents' 2nd payment through the Flex app. Read more on Rescheduling HERE.For example, if residents' rent payment is $1,000 each month:Flex will pay the full rent payment amount ($1,000) on the due date.Flex will collect part of residents' rent (1st payment + processing fee) on the due date, no later than the 5th calendar day of the month.Flex will collect the rest (2nd payment + processing fee) on the 15th of the month, or residents' rescheduled date within the month.Flex will collect residents' membership fee on the 15th of the month.In addition, after residents make residents' first payment residents' 2nd payment becomes Flexible! You can move residents' 2nd payment to a day that works better for residents! Read more on Rescheduling HERE."},
# {"question": "I have roommates, can Flex pay only my portion of the rent?", "answer": "Yes! As long as residents can make partial payments on residents' rent portal, Flex can pay just residents' portion of the rent.After residents sign up for Flex, please reach out to HERE and confirm the exact amount residents want us to pay on residents' rent portal."},
# {"question": "Do I have to use the app?", "answer": "Yes. The only way to apply for Flex and stay on track with payments is through the app."},
# {"question": "How do I qualify to use Flex? A: Flex evaluates residents' eligibility using a variety of factors including residents' credit report information, residents' banking information, and other information about residents' payment history. Generally, customers who are fair or better credit, with sufficient deposits and average bank balances will qualify for Flex. Some properties may offer expanded approval to their residents.", "answer": "Yes. The only way to apply for Flex and stay on track with payments is through the app."},
# {"question": "What is fair credit?", "answer": "While each individual's credit situation is unique; generally, customers with fair or better credit haveMay have missed some payments on their accounts in the past, but are on time on their accounts nowLow or moderate credit usage overall, but may have 1-2 accounts that have high usage3 or more open accountsNo recent defaults or bankruptcy filings"},
# {"question": "Why do residents need my Social Security Number?", "answer": "To help the government fight the funding of terrorism and money laundering activities, Federal law requires all financial institutions to obtain, verify, and record information that identifies each person who opens an account.What this means for residents: When residents open an account, we will ask for residents' name, address, date of birth, and other information that will allow us to identify residents. We may also ask to see residents' driver's license or other identifying documents.Flex does not currently accept ITIN or other forms of identification, but we plan to begin accepting them soon."},
# {"question": "I’m not sure if I completed signing up, how do I know?", "answer": "If residents successfully completed sign up, residents will be able to see residents' account via the Flex app. We will also send residents a nice, friendly welcome email.If residents don’t receive an email, or the sign up question repeats each time residents open the Flex app, residents have not completed sign up!If residents aren’t sure, residents can always email us HERE."},
# {"question": "What is a rent portal?", "answer": "Online rent portals are used by many property management companies to allow renters to easily pay rent online.To be able to use Flex, residents' property management company must be able to collect rent through a rent portal. If residents currently pay residents' rent with a physical check and aren’t sure if residents' property management company offers an online rent portal, reach out to them and ask!"},
# {"question": "What should I do if I can’t find my rent portal during sign-up?", "answer": "Some properties may use rent portals that are not yet integrated with Flex. If residents are unable to find residents' rent portal or property, residents can submit a request to have it added by Flex.To help us respond to residents' request as quickly as possible, make sure to select “Property & Resident Portal” for the Issue category and include the following information in the description:Property nameProperty full addressProperty website URL"},
# {"question": "Why do I need to enter my rent portal credentials, and what should I do if I run into an error?", "answer": "Flex utilizes residents' rent portal credentials to securely access residents' rent bill and seamlessly submit residents' payment directly to residents' property. Flex fully protects residents' username, password, and other personal account information with bank-level AES-256 encryption. We employ all data security controls required to maintain our SOC2 Type 2 certification and are independently audited every year to ensure residents' information is protected.We recommend residents use a strong password that is unique to residents' rent portal. Additional information about password best practices is available HERE.If residents encounter an error when connecting residents' rent portal to Flex, here are some things to check for:1. Make sure residents have set up a rent portal account before residents sign up for Flex.Some properties use smaller rent portals that are not yet integrated with Flex. If residents' rent portal is not currently supported, please send us a request to add by reaching out HERE.Please include the address and name of the property to be added.2. Try to reset residents' password through residents' rent portal and try again. If residents are able to log into residents' rent portal directly with the credentials, and residents are still receiving an error, please reach out to our support team for help."},
# {"question": "My property doesn’t accept e-check or ACH payments. What do I do?", "answer": "t this time, Flex can only pay residents' rent through e-check or ACH payments. Ask residents' property management if this is a feature they can turn on in the online rent portal.If residents don’t have a rent portal or they still won’t accept that form of payment, unfortunately residents will be unable to use Flex."},
# {"question": "What if I pay my rent by check (or Zelle, Venmo or direct deposit, etc.)?", "answer": "Flex technology works by accessing the rent portal at residents' property. If residents' property management doesn’t have an online rent portal, then unfortunately Flex won’t work in residents' current situation. We recommend reaching out to residents' property to allow online payments."},
# {"question": "I wasn’t approved for Flex, now what?", "answer": "We evaluate residents' eligibility using a variety of factors including residents' credit report information, residents' banking information, and other information about residents' payment history. Most customers with fair or better credit will qualify for Flex. If residents failed to qualify we’ll send residents a letter detailing exactly why. You can reapply in 60 days."},
# {"question": "How does a Flex credit line work?", "answer": "Flex is a monthly subscription that splits residents' rent into two payments. Each month, Flex pays residents' full rent directly to residents' property when it’s due. You pay part of that total rent up front when rent is due and finance the rest with a Flex credit line. You have the flexibility to choose residents' second payment date later in the month to better align with residents' finances."},
# {"question": "How is my Flex credit line amount determined?", "answer": "The amount of residents' Flex credit line is determined based on factors like residents' Flex repayment history (only applicable to current users), residents' credit report information, and residents' credit score.Flex repayment history (for current users): Have residents paid residents' Flex account on time? Have residents ever been delinquent or had a payment returned for insufficient funds?Credit report information and credit scores may reflect the following:Payment history: Do residents pay residents' bills, including monthly credit card bills, on time? Have residents ever filed for bankruptcy or had a debt sent to collections?Current accounts: How many open accounts do residents have? What types of loans do residents haveAccount history: How long have residents had residents' current accounts? Have residents applied for new credit recently?Credit utilization ratio: How much credit are residents using compared to the amount of credit residents have available? What is residents' debt-to-income ratio?"},
# {"question": "How will fees work?", "answer": "Flex charges monthly membership fees as a subscription$14.99 standard membership fee for credit lines of $500 and above$6.99 membership fee for credit lines less than $500Flex also charges a payment processing fee, which is a percentage of the monthly rent payment based on residents' chosen payment method (0.75% for debit card and 3% for credit card). Flex services are offered at 0% APR from Blue Ridge Bank, N.A. Member FDIC."},
# {"question": "Do I have to use my full credit line amount each month?", "answer": "We believe in giving residents the most financial flexibility in paying residents' rent. You can adjust how much of residents' credit line amount residents want to use for the month directly in the Flex app (Settings -> Payment schedule). Please note that the credit line allocation residents choose will be the new default every month unless residents manually readjust it."},
# {"question": "Is my credit line reassessed every month?", "answer": "s long as residents make on-time payments to residents' Flex account, residents' Flex credit line amount will not be changed. However, we may reduce residents' credit line amount if residents' account falls delinquent or residents have insufficient funds to complete residents' Flex payments."},
# {"question": "How frequently will credit line evaluations be conducted and will these evaluations impact my credit?", "answer": "We conduct a one-time soft credit check when residents set up residents' Flex account. There are no additional soft credit checks after this initial evaluation. The soft credit check does not impact residents' credit, but missed payments on residents' Flex account could negatively impact residents' credit score. We perform ongoing monitoring of residents' credit profile and Flex payment history to determine continued membership eligibility.See more questions about Flex credit line amounts HERE."},
# {"question": "Why is my Flex credit line not equal to half my rent?", "answer": "Flex credit line amounts vary based on an individual’s eligibility and personal financial factors, and are not exclusively based on monthly rent amounts. This enables us to provide residents with an optimal credit line amount that better aligns with residents' financial profile and situation. Because residents' financial situation is ever-changing, we reassess residents' credit line amount on an ongoing basis, which allows us to grow with residents as residents use it."},
# {"question": "How can I get a higher credit line?", "answer": "One of the benefits of Flex credit lines is that Flex will regularly assess residents' credit and determine whether residents' assigned credit line amount is aligned with residents' personal financial profile and situation. While residents can’t request a higher credit line at the moment, Flex will have the ability to make appropriate adjustments to residents' credit line over time."},
# {"question": "Will my credit line amount change if my rent amount increases?", "answer": "No, residents' originally assigned credit line amount will continue to be in effect. To give residents the most flexible rent payment experience, our team is working to add functionalities to increase residents' credit line and add new rent amounts for qualifying Flex members. Stay tuned!"},
# {"question": "Can I still choose to split my payments evenly?", "answer": "Flex credit line amounts vary based on an individual’s eligibility, but residents can still split residents' monthly rent into two payments. Your 2nd payment amount can be adjusted (up to residents' approved credit line amount) directly in the Flex app (Settings -> Payment schedule). For more flexibility, residents can also complete residents' 2nd payment before its scheduled date, directly in the app."},
# {"question": "How do I know what my payment amounts will be?", "answer": "You can view residents' payment amounts and schedule in the Flex app at any time by navigating to the Schedule screen."},
# {"question": "Why did Flex change my credit line amount?", "answer": "Flex offers credit line amounts based on personal financial factors and residents' monthly rent. This enables us to provide residents with an optimal credit line amount that better aligns with residents' financial profile and situation. Because residents' financial situation is ever-changing, we reassess residents' credit line amount on an ongoing basis, which allows us to grow with residents as residents use it.See more questions about how Flex credit lines work HERE."},
# {"question": "How does my credit line amount impact my rent payments and my payment schedule?", "answer": "Rent PaymentsYour credit line amount will not impact the rent payments we make on residents' behalf, and residents' rent bill will always be paid in full directly to residents' property regardless of what residents' credit line amount is.Payment Schedule:Your credit line amount will impact residents' payment schedule because it dictates the maximum residents can borrow with residents' Flex Line of Credit each month. In other words, residents' credit line amount is how much of residents' rent residents can defer out as residents' second payment.The best news is that residents' 2nd payment amount can be adjusted (up to residents' approved credit line amount) directly in the Flex app by navigating to Settings > Payment schedule. We recommend exploring that feature to maximize the benefits of residents' credit line! Please note that the credit line allocation residents select will become the new default every month unless residents manually update it again.You can check residents' payment amounts and schedule in the Flex app at any time by going to the Schedule screen."},
# {"question": "How does Flex work?", "answer": "after enrolling with Flex, we automatically make residents' rent payment directly to residents' property when it's due each month.Each month, residents pay us back in two payments - residents' \"1st payment\" when residents' rent is due and residents' \"2nd payment\" on the 15th of the month or residents' rescheduled date within the month. You can manage residents' 2nd payment through the Flex app. Read more on rescheduling HERE.For example, if residents' rent payment is $1,000 each month:Flex will pay the full rent payment amount ($1,000) on the due date.Flex will collect part of residents' rent (1st payment + processing fee) on the due date, no later than the 5th calendar day of the month.Flex will collect the rest (2nd payment + processing fee) on the 15th of the month, or residents' rescheduled date within the month.Flex will collect residents' membership fee on the 15th of the month.There are no interest rates or late fees when residents use Flex! The Flex Services are offered for a monthly membership fee of $14.99, which includes access to a Flex Line of Credit account from Blue Ridge Bank at 0% APR. Flex also charges a payment processing fee, a percentage of the monthly rent payment based on the chosen payment method (0.75% for debit card and 3% for credit card), assessed on each repayment.For example, if residents' rent amount is $1,000, the payment processing fee for a debit card is $7.50 ($1,000 * 0.0075).If residents' rent amount is $1,000 and residents pay with a credit card, the payment processing fee is $30 ($1,000 * 0.03)."},
# {"question": "How much does Flex cost?", "answer": "The Flex Services are offered for a monthly membership fee of $14.99, which includes access to a Flex Line of Credit account from Blue Ridge Bank at 0% APR.Flex also charges a payment processing fee, a percentage of the monthly rent payment based on the chosen payment method (0.75% for debit card and 3% for credit card), assessed on each repayment.Let's breakdown a $1000 rent payment:If residents' rent amount is $1,000, the payment processing fee for a debit card is $7.50 ($1,000 * 0.0075).If residents' rent amount is $1,000 and residents pay with a credit card, the payment processing fee is $30 ($1,000 * 0.03)."},
# {"question": "What is Rent Reporting?", "answer": "Rent Reporting is a way to ensure that residents' recurring monthly payments are communicated to Credit Bureaus.Having residents' rent payment history reported can be a positive signal for creditworthiness. Improving residents' credit helps residents with future financial milestones such as getting a mortgage, purchasing a car, and renting a new apartment."},
# {"question": "How do I sign up for Rent Reporting?", "answer": "Once residents' property has enrolled, residents begin receiving recurring communications from Flex confirming opt-in for rent reporting. No additional actions are needed from the resident.Actively enrolled residents are able to opt-out at any point during the program."},
# {"question": "Which bureaus does Flex report to?", "answer": "Flex reports directly to TransUnion. We are looking to expand to Experian and Equifax shortly."},
# {"question": "Can Flex Rent Reporting hurt my credit score?", "answer": "No, Flex will only report successful rent payments as a way to help build-up residents' credit history.Note: Rent Reporting is separate from existing credit reporting for users who have a credit line with Flex."},
# {"question": "How do I know if my property offers Flex Rent Reporting?", "answer": "Residents at enrolled properties will receive monthly emails confirming their enrollment."},
# {"question": "What do I do if I am an existing user on Flex to split my rent?", "answer": "No additional action is needed from residents' end. A resident can be a part of both Flex’s flexible rent and rent reporting offerings."},
# {"question": "How do I unenroll from Flex Rent Reporting?", "answer": "If residents are actively enrolled, residents will receive an enrollment confirmation email from Flex each month several days prior to the start of the month. You are able to unenroll directly through that email."},
# {"question": "How much does rent reporting cost?", "answer": "For enrolled properties, Flex Rent Reporting is complimentary to all residents."},
# {"question": "How does the Flex Services monthly membership fee work?", "answer": "The monthly membership fee is billed each month residents have access to the Flex Line of Credit. Our goal is to make our services readily available whenever residents need them. As a result, this fee will be charged as long as residents' account remains active, allowing us to provide residents with the flexibility and accessibility residents deserve. It's important to note that even if residents' account is paused, residents will still have access to residents' line of credit, and therefore, the membership fee will continue to be charged.For residents' convenience, the Flex Services are designed to auto-renew every month. This means that unless residents actively cancel residents' membership by the monthly cut-off, it will be automatically renewed for the upcoming month. It's essential to note that if residents' account renews, residents will be billed the monthly membership fee for that month, regardless of whether residents choose to use Flex to make residents' next rent payment. Our aim is to ensure uninterrupted access to our services, and the auto-renewal feature aligns with that commitment.If residents decide to cancel residents' membership, please complete the cancellation process no later than 2 days before the end of the month. You can view detailed information on our cancellation process HERE."},
# {"question": "How is the payment processing fee calculated?", "answer": "For each month residents use Flex Services to pay residents' rent, we will charge residents a payment processing fee equal to 0.75% of residents' monthly rent payment amount if residents pay with a debit card.We will charge a payment processing fee equal to 3% of residents' monthly rent payment amount if residents pay with a credit card.For example, if residents' rent amount is $1,000, the payment processing fee for a debit card is $7.50 ($1,000 * 0.0075). If residents' rent amount is $1,000 and residents pay with a credit card, the payment processing fee is $30 ($1,000 * 0.03).The payment processing fee is payable to Flex and assessed on each repayment."},
# {"question": "What can I expect when my rent is due?", "answer": "Flex pays residents' rent between the last day of the month through the first 5 days.During this window, we check whether residents' linked card has available funds for residents' 1st payment plus card processing fee.Once Flex has verified available funds for residents' 1st payment, we pay residents' rent in full directly to residents' property and process residents' 1st payment.Because our rent pay process is automated, residents do not need to make any manual payments."},
# {"question": "If I sign up on the 1st of the month, will Flex submit my rent payment?", "answer": "Flex pays residents' rent between the last day of the prior month through the first 5 days of the month.If residents successfully sign up by the 3rd day of the month, there’s still enough time for Flex to submit residents' rent payment for that month.If residents enroll with Flex after the 3rd, we will set residents up for rent payment in the following month."},
# {"question": "I have roommates, can Flex pay only my portion of the rent?", "answer": "Yes! As long as residents can make partial payments on residents' rent portal, Flex can pay just residents' portion of the rent.After residents sign up for Flex, please reach out to HERE and confirm the exact amount residents want us to pay on residents' rent portal."},
# {"question": "I have a past due rent on my portal, will Flex still pay my upcoming rent?", "answer": "No, Flex cannot pay residents' rent in a new month if residents have a past due rent bill.If residents' rent portal has an overdue balance from a previous month(s), Flex will be unable to pay the new month's rent until residents' past due balance has been paid to residents' property."},
# {"question": "Does signing up for Flex affect my credit?", "answer": "No. Signing up for a Flex account won’t affect residents' credit. Flex performs a soft credit inquiry with TransUnion during the application process to ensure that residents are eligible to use Flex. Soft inquiries won’t show up on credit bureau reports requested to evaluate residents' credit-worthiness."},
# {"question": "Does Flex report my payment data to credit reporting agencies?", "answer": "Yes. Flex reports residents' payment behavior on residents' Flex account to TransUnion."},
# {"question": "How long will it take for my Flex payments to be reported on my credit?", "answer": "When using Flex, we report residents' payment history to TransUnion. It may take between 30-60 days for residents' Flex payment data to appear on residents' TransUnion credit report. The timing depends on when payments were made, and when residents first used Flex to pay residents' rent.If residents need immediate assistance with receiving a verification of payment, please contact us at help@getflex.com."},
# {"question": "How can using Flex build my credit history?", "answer": "When residents use the Flex Credit Line and make on-time payments, we report a history of positive payments to TransUnion. If residents do not make on-time payments, it may negatively affect residents' credit."},
# {"question": "Does Flex report my credit history to my property?", "answer": "No. We do not report residents' credit history to residents' property."},
# {"question": "Will late or missed payments be reported to the credit bureau?", "answer": "Yes. Flex reports residents' payment history to TransUnion and late or missed payments may have an adverse impact on residents' credit score."},
# {"question": "Does adding a credit card as a payment method impact my credit score?", "answer": "dding a credit card as a payment method will not negatively impact residents' credit score. However, please keep in mind when residents use a credit card to make payments on residents' Flex line of credit, missed or late payments  may negatively impact residents' credit score."},
# {"question": "Does Flex make mortgage payments?", "answer": "Unfortunately, we do not make mortgage payments at this time. Stay tuned!"},
# {"question": "Does Flex include utility charges when submitting a rent payment?", "answer": "Yes! Flex will update residents' rent payment each month to include the full amount posted on residents' online rent portal. If residents' property bundles utilities in the rent portal amount, this will be paid along with residents' rent charges.This happens automatically each month, so residents don't have to worry about notifying us if the amount fluctuates month over month."},
# {"question": "What is an adverse action notice and why did I receive one?", "answer": "n adverse action notice is a letter that a loan provider sends to a customer when they are denied credit. It’s designed to help customers understand why they were denied credit, and how to improve their chances of being approved in the future.If residents received an Adverse Action Notice from us, it means that residents' request for a Flex Line of Credit was not approved or that an existing credit line was decreased or canceled."},
# {"question": "Does Flex submit rent payments outside of the US?", "answer": "t this time, we make rent payments within the USA. Stay tuned as we grow for Flex!"},
# {"question": "Does Flex have a customer support number?", "answer": "We don’t have a direct customer support number. Why? Because we hate putting residents on hold, and reaching out to us HERE is a far faster way to get residents' issues solved and residents' questions answered."},
# {"question": "What are the Flex support hours of operation?", "answer": "The Flex team provides email support Monday through Sunday during the hours of 9AM - 7PM EST.We generally respond to all inbound requests within 24 hours."},
# {"question": "How do I resume Flex’s service for the upcoming month?", "answer": "To resume Flex’s service, simply submit a request directly in residents' Flex app. Resume requests must be submitted by the 3rd day of the month. For example, to resume Flex’s services for the June rent cycle, make sure to submit residents' resume request by June 3rd.Any requests that are submitted after the monthly cut off will resume residents' membership for the following rent payment cycle if approved.To submit the resume request, open the Flex app and go to Settings > Account > Membership > Resume service. Flex’s service will resume immediately."},
# {"question": "How do I request to pause Flex services?", "answer": "Open the Flex app, and go to Settings > Account > Membership > Pause service. Once requested, the app will confirm service is paused.Please note that all pause requests must be submitted at least 2 days before the end of the month to ensure that a new rent payment is not submitted by Flex."},
# {"question": "What happens to my account when I pause Flex services?", "answer": "If residents pause Flex’s servicesFlex will not pay residents' rent bill and residents’ll be responsible for paying them residents'self directly to residents' propertyFlex will continue to charge residents' monthly membership feeYour Flex credit line will remain open and will continue to be reported as open to TransUnion"},
# {"question": "When is it helpful to pause Flex services?", "answer": "Being able to pause Flex's services is helpful when residents need Flex to temporarily stop paying residents' rent bills. The best part about this feature is that it keeps residents' credit line open, enabling residents to easily resume service with just a touch of a button."},
# {"question": "How do I resume Flex services?", "answer": "Open the Flex app, and go to Settings > Account > Membership > Resume ServicePlease note that resume requests must be submitted by the 3rd of the month if residents want to resume service for that same month."},
# {"question": "How do I cancel my membership?", "answer": "You can cancel residents' Flex membership directly in residents' Flex app by going to Settings > Account > Membership > Cancel membership. You must cancel residents' Flex membership no fewer than 2 days prior to the end of the month to ensure residents' account does not renew for the following month. If residents proceed to cancel residents' membership with an outstanding balance remaining, that balance will be transferred to collections and may impact residents' credit score unless timely payments are made."},
# {"question": "What happens if I cancel my membership?", "answer": "If residents cancel residents' membershipFlex will stop paying residents' rent bill.You will lose access to residents' Blue Ridge Bank Flex Credit Line and report it as closed to TransUnion.Flex will stop charging all payments and fees. If residents proceed to cancel residents' membership with an outstanding balance remaining, that balance will be transferred to collections which may impact residents' credit score unless timely payments are made.You will still have access to the Flex app, but if residents want to use Flex again in the future residents must reapply."},
# {"question": "How do I reapply for Flex if my membership is canceled?", "answer": "If residents' membership is canceled, residents can simply navigate to residents' home screen and click the “Re-apply” button and then follow the onscreen questions."},
# {"question": "Account Suspension: What to Expect", "answer": "n account suspension refers to the temporary suspension of residents' Flex line of credit.Account suspension may occur if Flex is not used in accordance with our terms and conditions. This includes instances such as failing to settle a balance by the due date not having sufficient funds available for residents' 1st payment.When residents' account is suspended, certain changes occur that affect residents' Flex line of credit.A message will appear on residents' app's home screen stating \"Your Flex membership is currently suspended.\"You will temporarily lose access to residents' Flex line of credit, meaning Flex will not submit residents' rent payments during this period.In most cases, Flex will not charge a membership fee while residents' account is suspended. However, if residents still have an overdue balance, a membership fee will continue to be charged for each month until the balance is settled.If residents' account is suspended, residents can request to resume residents' membership at any time. In our decision-making process, we extensively evaluate a range of factors to ensure a comprehensive analysis. This may involve considering credit information, income specifics, and payment history.It's important to keep in mind that Flex may choose not to provide services to residents at any time, based on factors such as residents' creditworthiness, transaction history on our site, the landlord's account history, or any other valid reason."},
# {"question": "Are debit card payments secure?", "answer": "We take residents' data and security very seriously. All debit card transactions are SSL protected and encrypted. This ensures the integrity of residents' personal information as well as payment processing."},
# {"question": "What happens if my debit card expires?", "answer": "We will notify residents in advance when residents' card is reaching an expiration date. Changes to residents' expiration date can easily be made in the Flex app."},
# {"question": "What types of debit cards does Flex accept?", "answer": "We accept any US-based debit card."},
# {"question": "How do I update my debit card with Flex?", "answer": "To update the debit card on file, open the Flex app, then navigate to Settings—> Payment Method  —>Change Card. From there simply input residents' Debit payment information, save, and residents’re all set!"},
# {"question": "If I’m using a debit card with Flex, can I switch back to ACH when I want?", "answer": "We take safety and security very seriously. Debit cards are the safest option for our users. You will not be able to switch back to ACH once they have chosen the safer, easier option of a debit card with Flex."},
# {"question": "Can I use a prepaid or credit card for my repayment?", "answer": "Flex now accepts credit cards as a repayment option.Flex does not accept repayment by prepaid debit."},
# {"question": "I’m moving soon. Can I transfer my Flex account to my new place?", "answer": "If residents' property is eligible for Flex, yes! You can send us an email HERE to check whether residents' property is eligible. We will review and let residents know if residents are able to use Flex at residents' new property.Make sure to include the following information so we can move residents' account to the new property:- Property name- Property address- Link to residents' online rent portal- New expected rent amount"},
# {"question": "What is a billing statement and why did I receive one?", "answer": "billing statement is a monthly report issued to account holders at the end of each billing cycle.Each billing statement includes the balance from the previous billing cycle, the balance due, payment due dates and other important information."},
# {"question": "What do I do if I find a mistake on my billing statement?", "answer": "One of the most important reasons to thoroughly review residents' billing statement is to verify that everything is correct. If residents see an error, please contact us HERE."},
# {"question": "What do I do if I find a mistake on my billing statement?", "answer": "One of the most important reasons to thoroughly review residents' billing statement is to verify that everything is correct. If residents see an error, please contact us HERE."},
# {"question": "What is a privacy notice and why did I receive one?", "answer": "privacy notice explains our policies and procedures on the collection, use, and disclosure of residents' personal information when residents are using the Flex Services.We send out a copy of our privacy notice annually, but it can also be accessed in the Privacy section of residents' Flex app or HERE at any time"},
# {"question": "What does it mean when Flex says it’s “not paid”?", "answer": "Your rent bill was not paid directly to residents' portal by Flex this month."},
# {"question": "What does “scheduled” mean?", "answer": "n upcoming rent bill that is scheduled is a bill that Flex will  pay directly to residents' portal on a pre-selected date, unless there is a technical issue."},
# {"question": "What is the last day Flex can pay residents' rent?", "answer": "Flex pays residents' rent between the last day of the prior month and the first 5 days of the current month. Funds must be available by 1pm EST on the 5th in order for a rent payment to be successfully submitted.During this window, we check whether residents' linked card has available funds for residents' 1st payment. Funds must be available by 1pm EST on the 5th in order for a rent payment to be successfully submitted.Once Flex has verified available funds for residents' initial payment, we pay residents' rent in full directly to residents' property and process residents' 1st payment.This process is automated and requires residents to make no manual payments.If we are unable to authorize residents' initial payment by the 5th day of each calendar month by 1pm EST, residents will be unable to access Flex to pay residents' rent in that month."},
# {"question": "What is a \"service issue\"?", "answer": "service issue is an error that has caused or may prevent residents' rent bill from being paid directly to residents' portal."},
# {"question": "What happens if I don’t do anything?", "answer": "If residents fail to take appropriate action in a timely manner, it may result in Flex being unable to pay residents' rent bill directly to residents' portal for that month. Once residents are notified of an issue, we recommend that residents take action ASAP to ensure residents' rent is paid."},
# {"question": "How will I know there is an issue?", "answer": "We will notify residents if we see an issue requiring action via residents' email account and SMS. You can also check the app to see if any issues have been raised that require action."},
# {"question": "How can I resolve a \"service issue\"?", "answer": "Simply log in to the Flex app, navigate to where a \"service issue\" is indicated on the home screen, and then follow the questions."},
# {"question": "Why do I need to re-link my property?", "answer": "There are times in which we lose connection to residents' property and will request that residents go into the app to reconnect it. Once reconnected, we’ll be able to continue the payment process.  One example of why this can occur is if residents recently changed residents' username and password to residents' property portal."},
# {"question": "What do I need to do to re-link?", "answer": "To re-connect, simply log in to the Flex app, navigate to where a \"service issue\" is indicated and follow the questions. You will need to input residents' address, select residents' property and then go through the necessary steps to connect residents' property. For some, it may be as simple as selecting residents' unit, for others residents may be required to provide a username or password."},
# {"question": "Why do I need to confirm my rent amount?", "answer": "There are instances in which the rent bill amount we get from residents' property differs greatly from the estimated rent amount residents provided. In these cases, we’ll need residents to confirm the rent amount before we can proceed with paying residents' rent to make sure we pay as accurately as possible."},
# {"question": "What do I need to do?", "answer": "To confirm residents' rent amount, simply log in to the Flex app, navigate to where a \"service issue\" is indicated, and then follow the questions. You will see the rent bill amount we retrieved vs. the estimated rent residents provided and residents can confirm the amount residents’d like to pay."},
# {"question": "Why was my 1st payment unable to be completed?", "answer": "In order to pay residents' rent, we require residents' 1st payment as indicated during sign-up and in residents' in-app schedule. If we attempt to process residents' 1st payment, and residents do not have sufficient funds, we will notify residents via email or SMS. Another reason Flex may be unable to process residents' 1st payment may be that residents' payment method is no longer valid."},
# {"question": "What do I need to do?", "answer": "There are a few things residents can do1. You can follow in-app questions and update residents' payment method. This generally will solve issues where the previous payment method was invalid.2. You can wait for Flex to retry residents' payment. We generally will try payment two times daily until 1pm EST on the 5th of the month. We recommended ensuring residents have sufficient funds for residents' first payment plus the card processing fee as soon as residents’re notified.3. You can reattempt residents' 1st payment directly in the Flex app. We recommended ensuring residents have sufficient funds for residents' first payment plus the card processing fee as soon as residents’re notified."},
# {"question": "I was told that my rent payment is not going through. Why?", "answer": "This generally occurs if residents' property has some sort of technical issue with payments. Most issues tend to be related to residents' property having disabled ACH/bank transfer payments. We’ll continue to try to pay residents' rent bill directly to residents' portal but we may not be successful if this issue persists."},
# {"question": "What do I need to do?", "answer": "We recommend that residents reach out to residents' property to confirm if there are any issues and to re-enable ACH if it was disabled. It’s possible residents' property is already aware of the issue and is fixing it but we still recommend reaching out to increase the likelihood and expediency in which the issue can be resolved.Flex will continue to retry payment so as long as residents' property re-enables ACH before the 5th, we should be able to get residents' rent paid."},
# {"question": "What happens if my rent doesn't get paid on time and my property charges me a late fee?", "answer": "When paying with Flex, the vast majority of late fees are caused when a customer’s linked debit card lacks sufficient funds for Flex to authorize their first payment before the property begins charging a late fee. These late fees can be avoided by ensuring residents have enough money in residents' linked debit card for Flex to authorize the first payment as soon as rent is due, usually the last day of the prior month or the first day of the current month.However, if there is ever a delay in rent being paid due to an issue on Flex’s end, we will reimburse residents. Fortunately, this is rare, as we have only seen it happen less than 0.4% of the time and is largely due to technical challenges arising from integrating with dozens of different rent payment systems. Additionally, if that happens, qualifying Flex members will have access to a Flex-funded payment method once Flex has been able to authorize the first payment.If residents think an error was made, simply submit a request to contact our support team. Our team of experts will review residents' situation and we will reimburse late fees incurred because of a Flex-caused delay in residents' rent being paid on-time."},
# {"question": "Can I reschedule my 2nd payment?", "answer": "Yes! Open the Flex app and go to Settings > Payments Dates. From there, follow the questions and select the date that works for residents. If residents don’t see the date residents’re looking for, please contact our support. You can reschedule to any business day up to the last 6 days of the month.Please keep in mind that this change will only change the upcoming payment and next month’s payment will revert back to the default date."},
# {"question": "How many times can I reschedule a payment?", "answer": "Having a month that needs extra flexibility? We’ve got residents.You can reschedule residents' second payment within the month it is due. Please keep in mind, though, that: (1) payments need to be rescheduled at least 1 business day in advance; and (2) residents must have a zero balance at the end of the month to remain eligible for Flex services in future months.To re-schedule residents' payment, make sure residents've updated to the latest version of the Flex app and then navigate to Settings > Repayment Date. From there, hit the Update button to select a new eligible date for residents' repayment."},
# {"question": "Can I split my monthly payments into smaller payments?", "answer": "Each month, residents pay us back in two payments - residents' 1st payment when residents' rent is due and the rest on the 15th of the month or residents' rescheduled date within the month. You can manage residents' 2nd payment through the Flex app. Read more on rescheduling HERE.For example, if residents' rent payment is $1,000 each month:Flex will pay the full rent payment amount ($1,000) on the due date.Flex will collect part of residents' rent (1st payment + processing fee) on the due date, no later than the 5th calendar day of the month.Flex will collect the rest (2nd payment + processing fee) on the 15th of the month, or residents' rescheduled date within the month.Flex will collect residents' membership fee on the 15th of the month.The 2nd payment can be split into smaller payments or rescheduled within the month as needed.To make a split payment request for residents' 2nd monthly payment, please reach out HERE."},
# {"question": "Can I schedule my 2nd payment to be made on the last day of the month?", "answer": "Yes. However, by scheduling residents' 2nd payment to the last day of the month, there is a risk that residents will be unable to use Flex the following month.YOU MUST PAY YOUR TOTAL DUE IN FULL EACH MONTH OR YOU WILL BE UNABLE TO ACCESS THE BLUE RIDGE BANK FLEX CREDIT LINE TO PAY YOUR RENT IN THE FOLLOWING MONTHFlex allows residents to reschedule residents' 2nd payment up to 3 business day before residents' scheduled payment. You can reschedule residents' 2nd payment of each month on the Flex app or by reaching out to the Flex team HERE."},
# {"question": "How can I pay off my balance on my own?", "answer": "Flex members are able to proactively pay off their balance directly in the Flex app. If residents have an outstanding balance, residents should have access to the “Make payment” button on the Flex app home screen under “Schedule”.When residents decide to “Make payment” in-app, residents should be aware of the following:You are agreeing to pay off the total full balance on residents' account.If residents decide to make the payment now, residents are moving forward the scheduled charge communicated during the bill payment cycle.Repaying Flex now is a one-time feature and will not impact any future auto-pay instances.Once payment is successful, the balance will be $0, and the “Pay” button will be disabled until the next time residents use Flex to pay residents' rent.If residents' payment fails, the originally scheduled balance will remain and will be executed as originally scheduled."},
# {"question": "Can I make a payment early?", "answer": "Flex is unable to process residents' first monthly payment until residents' rent for that month has been paid by Flex.If residents'd like to make residents' 2nd monthly payment ahead of residents' scheduled date, residents can do so at any time in the Flex app, or by reaching out to the Flex team HERE."},
# {"question": "Can I reschedule my 2nd payment for the month to a future month?", "answer": "No. YOU MUST PAY YOUR TOTAL DUE IN FULL EACH MONTH OR YOU WILL BE UNABLE TO ACCESS THE BLUE RIDGE BANK FLEX CREDIT LINE TO PAY YOUR RENT IN THE FOLLOWING MONTH."},
# {"question": "Help, I missed a payment! Can I still use Flex to pay my rent?", "answer": "Yes. You can continue to use Flex as long as residents reschedule all missed payments and have no outstanding balance at the end of the month. You can reschedule residents' second payment of each month on the Flex app or send a reschedule request to the Flex team HERE.NOTE: You must pay residents' total due in full each month, or residents will be unable to access the Flex line of credit to pay residents' rent the following month. Flex reports residents' payment history to TransUnion and late or missed payments may have an adverse impact on residents' credit score."},
# {"question": "Does Flex charge late fees or penalties for missed payments?", "answer": "There are no interest rates or late fees when residents use Flex! Flex charges a standard monthly membership fee of $14.99. Flex also charges a payment processing fee, a percentage of the monthly rent payment based on the chosen payment method (0.75% for debit card and 3% for credit card), assessed on each repayment.For example, if residents' rent amount is $1,000, the payment processing fee for a debit card is $7.50 ($1,000 * 0.0075). If residents' rent amount is $1,000 and residents pay with a credit card, the payment processing fee is $30 ($1,000 * 0.03)."},
# {"question": "Help, I can’t pay my balance! Can I set up a payment plan?", "answer": "We understand that unexpected financial situations can arise, and we're here to support residents during such times. If residents find residents'self unable to pay off residents' balance by the deadline specified in our terms and conditions, we offer the option to set up a payment plan, which will allow residents to gradually pay off residents' balance over an agreed-upon period of time.To avoid any negative impact on residents' credit report, it's important to reach out to us before residents' account becomes delinquent if residents anticipate not being able to settle residents' balance by the end of the month. By setting up the payment plan before residents' account falls into delinquency and making timely payments as agreed upon, residents' account will continue to be reported as on-time to the credit bureaus.It's also worth noting that setting up a payment plan and deferring residents' balance to a future month will result in the suspension of residents' Flex Line of Credit and residents' account may be reported as a late payment to the credit bureau which could have a negative impact on residents' credit history. To keep residents' account active and maintain access to residents' Line of Credit, it's necessary to settle all balances in full by the end of each month.The availability of a payment plan may vary for different accounts, but we'll do our best to accommodate residents' needs."},
# {"question": "If I’m on a payment plan do I still get charged the membership fee each month?", "answer": "Yes, residents will be charged the Flex monthly membership fee until residents' balance is paid and residents pause or cancel residents' Flex account."},
# {"question": "Flex didn’t pay my rent this month, will I still be charged the membership fee?", "answer": "If residents' account was active, but Flex couldn't submit residents' rent payment due to an unresolved issue, residents won't be charged a membership fee for that particular month.However, if service was paused, a membership fee will be charged as residents' Flex line of credit remains open in a paused state. You can find additional details about what happens when residents pause service HERE."},
# {"question": "When is the Flex monthly membership fee charged?", "answer": "Flex charges the standard monthly membership fee of $14.99 on the 15th of the month."},
# {"question": "What if I don't have funds for my 1st payment?", "answer": "Our technology requires that residents have the funds for residents' first payment before we can pay residents' rent on the 1st. As long as residents add those funds by the 5th, we can still pay residents' rent. Unfortunately, Flex won’t be able to pay residents' rent for any month where residents don’t have the first payment funds available by 1pm on the 5th.If this is the case, residents' credit line may be reduced or suspended. You can read more about what happens when Flex’s service is paused HERE."},
# {"question": "What is the deadline for a resident to sign-up to use Flex to pay their rent?", "answer": "Flex pays user rent between the last day of the prior month through the first 5 days of the month.As long as residents are successfully signed up by the 3rd day of the month BEFORE 5pm EST, there’s still enough time to process residents' payment for that month.If they enroll with Flex after 5PM EST on the 3rd, we will set them up for rent payment in the following month."},
# {"question": "Who qualifies to use Flex?", "answer": "We evaluate applicant eligibility using a variety of factors including credit report information, banking information, and other information about the applicant's payment history. Most customers with fair or better credit will qualify for Flex. If the applicant failed to qualify we’ll send the applicant a letter detailing exactly why. They can reapply in 60 days."},
# {"question": "Does applying for Flex affect a resident’s credit score?", "answer": "During the application process, Flex runs a soft credit check on the resident which does not affect their credit score."},
# {"question": "How much does Flex charge?", "answer": "Flex charges a standard monthly membership fee of $14.99. Flex also charges a payment processing fee, a percentage of the monthly rent payment based on the chosen payment method (0.75% for debit card and 3% for credit card), assessed on each repayment.For example, if residents' rent amount is $1,000, the payment processing fee for a debit card is $7.50 ($1,000 * 0.0075). If residents' rent amount is $1,000 and residents pay with a credit card, the payment processing fee is $30 ($1,000 * 0.03)."},
# {"question": "What are the reasons why resident rent wouldn’t be submitted by Flex even after they are approved?", "answer": "Flex is constantly adapting to many factors in real time. There are a few reasons why a rent payment may not be submitted by Flex for residents that are approvedThey do not have enough funds in their bank account to complete their first payment to Flex at the beginning of the month.They use a debit or credit card with Flex that has expired.The authorization of their required first payment is not successful.They have a past due or outstanding balance on their rent ledger.ACH is disabled on their online rent portal and was not enabled by the 5th.Their posted rent bill amount is incorrect or not available."},
# {"question": "What happens if a resident doesn’t pay Flex back?", "answer": "We know times can be tough, and we believe in going the extra mile to help people keep their commitments. We can even set up a payment plan HERE to help residents pay back over time.If the worst happens and a resident is unable to pay us back, we handle all write offs internally, and never pass this expense back to a property. It’s important to remember that not keeping a commitment with Flex will negatively affect a resident’s credit score. Flex reports residents' payment history to TransUnion and late or missed payments may have an adverse impact.If a resident is part of a payment plan, once the payment plan has been completed, they will be once again eligible to use Flex."},
# {"question": "What does a resident need to do if they no longer want to use Flex?", "answer": "Most residents prefer to pause Flex instead of canceling their membership. Pausing stops Flex from paying their rent bills until they indicate that they’d like to resume Flex’s services.PAUSE: If a resident does not wish to use Flex to pay their rent payment in a specific month, they may pause Flex’s services by navigating to Settings > Account > Membership > Pause service. The pause option allows residents to pause Flex’s services and keep their Blue Ridge Bank Flex Credit Line account open and report it as open to TransUnion.Please note, paused accounts will continue to be charged the monthly membership fee on the 15th of each month. All pause requests must be submitted at least 2 days before the end of the month to ensure that a new rent payment is not processed.CANCEL: Residents can cancel their Flex membership by going to Settings > Account > Membership > Cancel membership within the Flex app. When an account is canceled, we will close the Blue Ridge Bank Flex Line of Credit account and report it as closed to TransUnion. If a resident proceeds to cancel their membership with an outstanding balance remaining, that balance will be transferred to collections which may impact their credit score unless timely payments are made.Residents must cancel their Flex membership no fewer than 2 calendar days prior to the end of the month or they will be charged the monthly membership fee on the 15th of the following month, regardless of whether they use Flex to pay their rent for the month."},
# ]

FAQ_list = [
    {
        "question": "What is a privacy notice and why did I receive one?",
        "answer": "privacy notice explains our policies and procedures on the collection, use, and disclosure of residents' personal information when residents are using the Flex Services.We send out a copy of our privacy notice annually, but it can also be accessed in the Privacy section of residents' Flex app or HERE at any time",
    },
    {
        "question": "What does it mean when Flex says it’s “not paid”?",
        "answer": "Your rent bill was not paid directly to residents' portal by Flex this month.",
    },
    {
        "question": "What does “scheduled” mean?",
        "answer": "n upcoming rent bill that is scheduled is a bill that Flex will  pay directly to residents' portal on a pre-selected date, unless there is a technical issue.",
    },
    {
        "question": "What is the last day Flex can pay residents' rent?",
        "answer": "Flex pays residents' rent between the last day of the prior month and the first 5 days of the current month. Funds must be available by 1pm EST on the 5th in order for a rent payment to be successfully submitted.During this window, we check whether residents' linked card has available funds for residents' 1st payment. Funds must be available by 1pm EST on the 5th in order for a rent payment to be successfully submitted.Once Flex has verified available funds for residents' initial payment, we pay residents' rent in full directly to residents' property and process residents' 1st payment.This process is automated and requires residents to make no manual payments.If we are unable to authorize residents' initial payment by the 5th day of each calendar month by 1pm EST, residents will be unable to access Flex to pay residents' rent in that month.",
    },
]


# "I am an AI chatbot trained to answer questions about Company X. Below are some examples of questions and accurate answers based on Company X's FAQ:"
# "You: I'm going to provide you with a list of frequently asked questions and answers about my company. Please use this information to answer similar questions."
def generate_interaction_prompt(question, faq_list: [], max_length: int = 300):
    prompt = [
        {"role": "system", "content": "You are a FAQ assistant"},
        {
            "role": "user",
            "content": "Below are some examples of questions and accurate answers based on Flex's FAQ"
            + "\n".join([f"{faq['question']}\n {faq['answer']}\n" for faq in faq_list]),
        },
        {
            "role": "assistant",
            "content": f"Sure, I will answer your question based on the FAQ I have learned.I will ensure that responses "
            f"are concise, no more than {max_length} words each, and provide clear, complete information for each inquiry."
            f"I will also make the tone as I am talking to a thrid party, not directly to users.",
        },
        {"role": "user", "content": f"question: {question}"},
    ]
    return prompt


# # Start a new chat session
# start_sequence = "\nAI:"
# restart_sequence = "\nHuman: "
#
# # This will be your initial prompt, providing the AI with its role and the FAQ context.
# initial_prompt = "The following is a list of FAQs about my company. You are a knowledgeable assistant who will use this information to answer questions.\n\n"
#
# # Add your FAQ pairs here
# faq_content = """Q: What are your business hours?
# A: Our business hours are from 9 am to 5 pm, Monday to Friday.
# Q: Do you offer international shipping?
# A: Yes, we offer international shipping to over 50 countries.
# Q: How can I track my order?
# A: Once your order has shipped, you will receive an email with a tracking number. You can use this number on our website to check the status of your delivery.
# """
#
# # Combine initial prompt with FAQ content
# chat_history = initial_prompt + faq_content


def ask_question(chat_history):
    # Append the user's question to the chat history
    # prompt_text = chat_history + restart_sequence + question + start_sequence

    # Make the API call to GPT-3
    # response = openai.ChatCompletion.create(
    #     model="gpt-3.5-turbo",
    #     prompt=chat_history,
    #     temperature=0.7,
    #     max_tokens=150,
    #     top_p=1,
    #     frequency_penalty=0,
    #     presence_penalty=0,
    #     # stop=["\nHuman:", "\nAI:"],
    # )

    # Extract the AI's response and append it to the chat history
    response = openai.ChatCompletion.create(
        model="gpt-4-1106-preview",
        messages=chat_history,
    )
    return response["choices"][0]["message"]["content"]


question = "When Flex pay residents' rent"
chat_history = generate_interaction_prompt(question, FAQ_list, max_length=100)
result = ask_question(chat_history)
print(result)
# Example usage of the function
# user_question = "How do I return a purchased item?"
# answer, chat_history = ask_question(user_question, chat_history)
# print(f"AI: {answer}")

# Now, chat_history contains the entire conversation, including the AI's response
# You can continue to pass chat_history to ask_question for further queries
