# import streamlit as st
#
# # Create a Streamlit app
# st.title("Generate Button on Click")
#
# # Create the first button
# button1_clicked = st.button("b1")
# button2_clicked = st.button("b2")
# # Check if the first button is clicked
# if button1_clicked:
#     st.write("You clicked the first button.")
# if button2_clicked:
#     st.write("You clicked the second button.")
#
# import streamlit as st
#
# # Create a Streamlit app
# st.title("Persist Content with Session State")
#
# # Initialize session state
# if 'content' not in st.session_state:
#     st.session_state.content = []
#
# # Create button1 to generate content
# button1 = st.button("Click me to generate content")
#
# # Check if button1 is clicked
# if button1:
#     st.session_state.content.append("This content is generated by button1.")
#
# # Display the content
# st.write(st.session_state.content[0] if st.session_state.content else "")
#
# # Create button2 to clear the content
# button2 = st.button("Click me to clear content")
#
# # Check if button2 is clicked
# if button2:
#     st.session_state.content = []
# import streamlit as st
#
# # Create a Streamlit app
# st.title("Generate Multiple Text Areas")
#
# # Create a button to generate text areas
# generate_button = st.button("Generate Text Area")
#
# # Initialize a list to store text areas
# text_areas = []
#
# # Check if the button is clicked
# if generate_button:
#     # Append a new text area to the list
#     text_areas.append(st.text_area(f"Text Area {len(text_areas) + 1}", ""))

import streamlit as st
import random


if "content" not in st.session_state:
    st.session_state["content"] = {}


def add_new_row(new_key, new_value):
    # st.session_state['champs_dict'][new_champ] = st.text_input(new_champ+'...', key=new_champ+str(random.randint(0,999999)))
    st.session_state["content"][new_key] = (new_value, st.write(new_value))


new_champ = st.text_input("Please enter the new champ...", key="new_champ")
add_new = st.button("Add new row")
if add_new:
    if new_champ not in st.session_state["content"]:
        print("state:")
        print(st.session_state["content"])
        nv = str(random.randint(0, 999999))
        st.session_state["content"][new_champ] = (nv, None)
        for key in st.session_state["content"]:
            print("key: " + key)
            print("state key: ")
            print(st.session_state["content"][key])
            nnv = st.session_state["content"][key][0]
            add_new_row(key, nnv)

    else:
        st.warning(str(new_champ) + " exists already!")
        for key in st.session_state["content"]:
            add_new_row(key, "xxx")
# import streamlit as st
#
# # Create a Streamlit app
# st.title("Text Input with Default Content")
#
# # Create a text input widget with a default value
# default_text = "This is the default content"
# user_input = st.text_input("Enter Text", default_text)
#
# # Display the user input
# st.write(f"You entered: {user_input}")
